# Numpy
* stands for numerical Python
* numpy is a python library used for working with arrays
* has function for working in domain of linear algebra, fourier transform and matrices
* numpy array is a collection of homogeneous data types stored in contiguous memory location
* written partially in python, but parts that require fast computation are written in C or C++

#  Why is Numpy so fast?
* An array is a collection of homogeneous data types that are stored in contiguous memory location
* Vectorized operations are possible in Numpy
* Numpy package integrates C, C++ and Fortran codes in python

In [1]:
import numpy as np

# Create numpy array vai 1D list

In [2]:
np.random.seed(0)
list_1 = np.random.randint(low=1, high=20, size=10)
arr = np.array(list_1)
print(arr)

[13 16  1  4  4  8 10 19  5  7]


# Checking the type of array

In [3]:
type(arr)

numpy.ndarray

# create numpy via 2D list

In [4]:
list_2 = np.random.randint(low=10, high=30, size=10)
arr_2 = np.array([list_1, list_2], dtype="float32")
arr_2

array([[13., 16.,  1.,  4.,  4.,  8., 10., 19.,  5.,  7.],
       [22., 11., 16., 17., 24., 27., 15., 23., 18., 19.]], dtype=float32)

# .shape

In [5]:
arr_2.shape

(2, 10)

# .ndim

In [6]:
arr_2.ndim

2

# .zeros()

In [7]:
np.zeros((3, 3), dtype="int")

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [8]:
np.zeros(10, dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
np.zeros((5, 2), dtype="int")

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

# .ones()

In [10]:
np.ones(3, dtype="int")

array([1, 1, 1])

In [11]:
np.ones([3, 5], dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# .full()

In [12]:
np.full([2, 3], 3.23)

array([[3.23, 3.23, 3.23],
       [3.23, 3.23, 3.23]])

In [13]:
np.full([2, 2], ["white", "green"])

array([['white', 'green'],
       ['white', 'green']], dtype='<U5')

In [14]:
np.full((2, 10), [list_1, list_2])

array([[13, 16,  1,  4,  4,  8, 10, 19,  5,  7],
       [22, 11, 16, 17, 24, 27, 15, 23, 18, 19]])

# .arange()

In [15]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(3, 23)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22])

# .random()

In [18]:
np.random.random((3, 5))

array([[0.64817187, 0.36824154, 0.95715516, 0.14035078, 0.87008726],
       [0.47360805, 0.80091075, 0.52047748, 0.67887953, 0.72063265],
       [0.58201979, 0.53737323, 0.75861562, 0.10590761, 0.47360042]])

In [19]:
np.random.randint(3, 534)

513

In [20]:
np.random.random((2, 5))

array([[0.77423369, 0.45615033, 0.56843395, 0.0187898 , 0.6176355 ],
       [0.61209572, 0.616934  , 0.94374808, 0.6818203 , 0.3595079 ]])

# .normal()

In [21]:
data = np.random.normal(loc=3, scale=1, size=(3, 3))
data

array([[4.78748405, 2.43048274, 3.17538653],
       [2.53749446, 1.9141994 , 3.63973599],
       [2.61413666, 2.22423765, 3.99571135]])

# .randint()

In [22]:
np.random.randint(low=0, high=10, size=(3, 3))

array([[4, 4, 6],
       [4, 4, 3],
       [4, 4, 8]])

# Creating Sample Array

In [23]:
sample_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sample_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
# Printing the dimension of numpy
sample_array.ndim

2

In [25]:
sample_array.shape

(3, 3)

In [26]:
reshape_array = sample_array.reshape(1, 3, 3)
reshape_array

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [27]:
reshape_array.shape

(1, 3, 3)

In [28]:
reshape_array.ndim

3

In [29]:
reshape_array.size

9

In [30]:
reshape_array.dtype

dtype('int32')

In [31]:
reshape_array.itemsize

4

In [32]:
np.array(["Alone", "Home", 10, True, 0, 44.2])

array(['Alone', 'Home', '10', 'True', '0', '44.2'], dtype='<U32')

In [33]:
import numpy as np

In [34]:
type(np.array((3, 4)))

numpy.ndarray

# Function that converts list into another list which act as array like structure

In [35]:
def to_array(data):
    """
    Function that converts the list data into array like structure

    args: takes argument as list of elements

    return : return data in specific datatype
    """

    string = []
    flo = []
    integer = []
    boolean = []
    # tuple = []
    # list = []

    # checking type of data and appending in respective datatype
    for item in data:
        if isinstance(item, str):
            string.append(item)
        elif isinstance(item, float):
            flo.append(item)
        elif isinstance(item, bool):
            boolean.append(item)
        elif isinstance(item, int):
            integer.append(item)

    # print(len(string), len(flo), len(integer), len(boolean))

    # if datatype of any data is string convert all data into string
    if len(string) > 0:
        arr_data = [str(i) for i in data]
    
    # if there is no string and datatype contains float numbers then convert all data into float numbers
    elif len(flo) > 0:
        arr_data = [float(i) for i in data]
    
    # if there is no sting and float datatype in the data then convert all the data into int 
    elif len(integer) > 0:
        arr_data = [int(i) for i in data]
    
    # else keep the boolean data same
    elif len(boolean) > 0:
        arr_data = data

    return arr_data


# Testing

In [36]:
# data that contains string
to_array(data=[True, 2.3, "Home", "Alone", 34])

['True', '2.3', 'Home', 'Alone', '34']

In [37]:
# data that contains float but not string
to_array(data=[4, True, False, 45, 2.2])

[4.0, 1.0, 0.0, 45.0, 2.2]

In [38]:
# data that contains int but not float and string
to_array(data=[4, False, 2, 5, 2, True])

[4, 0, 2, 5, 2, 1]

In [39]:
# data that contains bool only
to_array(data=[True, False, False])

[True, False, False]

In [40]:
np.array([[True, 0, 3], [True, 0, 9.3]])


array([[1. , 0. , 3. ],
       [1. , 0. , 9.3]])

In [41]:
type(to_array)

function

In [42]:
isinstance(True, int)

True

In [43]:
isinstance(False, int)

True

In [44]:
np.array([[3, 54, "10"], [2, 4, 9.2]])

array([['3', '54', '10'],
       ['2', '4', '9.2']], dtype='<U32')

In [45]:
float(2.3)

2.3

In [46]:
np.array([3, "2", 2])

array(['3', '2', '2'], dtype='<U11')

In [47]:
datas = ["3", 3, 2.3]
isinstance(datas, str)

False

In [48]:
np.array([3, "2", 2])

array(['3', '2', '2'], dtype='<U11')

In [49]:
arr_01 = np.array([2, 3, 2, 34])
arr_01

array([ 2,  3,  2, 34])

In [50]:
arr_01 = np.array([2, 43.3, "alone", True], dtype="int")
arr_01

ValueError: invalid literal for int() with base 10: 'alone'

In [ ]:
arr_01 = np.array([2, 4.2, "Alone", True], dtype="object")
arr_01

array([2, 4.2, 'Alone', True], dtype=object)

# Array Indexing

In [ ]:
# indexing 1D array
a = np.random.randint(3, 10, 10)
a

array([4, 6, 3, 8, 9, 3, 4, 5, 7, 5])

In [ ]:
l = [3, 2, 23, 55]
id(l[0])

140715698670072

In [51]:
id(l[1])

NameError: name 'l' is not defined

In [52]:
a

NameError: name 'a' is not defined

In [53]:
print(f"1st_item: {a[0]}")
print(f"2nd item: {a[1]}")
print(f"3rd item: {a[2]}")
print(f"last_item: {a[-1]}")

NameError: name 'a' is not defined

In [54]:
print(id(a[0]), id(a[1]), id(a[2]))

NameError: name 'a' is not defined

# 2D array

In [55]:
arr_idx_2d = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
arr_idx_2d

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [56]:
print(arr_idx_2d[0, 0])
print(arr_idx_2d[2, 2])
print(arr_idx_2d[1, 1])
print(arr_idx_2d[2, 0])

11
33
22
31


In [57]:
# example array
arr_1 = np.array([1, 2, 3, 4, 5, 6, 7])
arr_1_slice = arr_1[1:7:2]
arr_1_slice

array([2, 4, 6])

In [58]:
arr_1[1:-1]

array([2, 3, 4, 5, 6])

In [59]:
arr_1[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [60]:
arr_idx_2d[::2,2:]

array([[13],
       [33]])

In [61]:
arr_1[-3:-1] # left to right

array([5, 6])

# Reverse

In [62]:
arr_1[::-1]

array([7, 6, 5, 4, 3, 2, 1])

# Slicing 2D array

In [63]:
arr2 = np.array([
    [11, 12, 13],
    [21, 22, 23],
    [31, 32, 33]
])

In [64]:
arr2[2:, 1:]

array([[32, 33]])

In [65]:
arr2[2:]

array([[31, 32, 33]])

In [66]:
arr2[:]

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [67]:
arr2[:2]

array([[11, 12, 13],
       [21, 22, 23]])

In [68]:
arr2[1:, :]

array([[21, 22, 23],
       [31, 32, 33]])

In [69]:
arr2[2:, 1:]

array([[32, 33]])

In [70]:
arr2

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [71]:
arr2[:1, 2:]

array([[13]])

In [72]:
arr2[1:, 1]

array([22, 32])

In [73]:
arr2

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

# copy arr

In [74]:
copy_arr = arr2.copy()

In [75]:
copy_arr

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [76]:
id(arr2)

1730704305552

In [77]:
id(copy_arr)

1730704307184

In [78]:
ls = [2, 3, 33, 22]
id(ls[0])

140715392682456

In [79]:
id(ls[1])

140715392682488

In [80]:
id(ls[2])

140715392683448

In [81]:
# copy_arr = arr2

In [82]:
id(copy_arr)

1730704307184

In [83]:
id(arr2)

1730704305552

In [84]:
copy_arr = np.copy(arr2)
print(f"""Do original array and copy array shares an memory?
      Ans: {np.shares_memory(arr2, copy_arr)}""")

Do original array and copy array shares an memory?
      Ans: False


In [85]:
# but while assigning array to copy array it shares same memory location (it is not copy)
copy_arr = arr2
print(f"""Do original array and copy array shares an memory?
      Ans: {np.shares_memory(arr2, copy_arr)}""")

Do original array and copy array shares an memory?
      Ans: True


# .view()

In [86]:
copy_arr = arr2.view()
id(copy_arr)

1730704307280

In [87]:
id(copy_arr)

1730704307280

In [88]:
l = [2, 4, 3]
id(l[0])

140715392682456

In [89]:
id(l[1])

140715392682520

In [90]:
id(l[2])

140715392682488

# .reshape()

In [93]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [98]:
np.reshape(arr, (2, 6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [99]:
arr.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [100]:
arr.reshape(-1, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [101]:
arr.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [102]:
np.reshape(arr, (4, 3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# to 3D

In [105]:
np.reshape(arr, (2, 3, 2))

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [116]:
# convert 1D array with 8 elements to a 2D array with spape (3, 3)

arr = np.array([3, 4, 2, 5, 2, 5, 2, 2])
arr.reshape(3, 3) # raise error as 3 * 3 is not 8

ValueError: cannot reshape array of size 8 into shape (3,3)

* This process raise an exception, since there are 8 elements before reshaping and 9 elements after reshaping
* for reshaping no. of elements before reshaping shouldbe equal to numer of elements after reshaping

In [113]:
arr.reshape(2, 4)

array([[3, 4, 2, 5],
       [2, 5, 2, 2]])

In [114]:
arr.reshape(2, 2, 2)

array([[[3, 4],
        [2, 5]],

       [[2, 5],
        [2, 2]]])

In [115]:
arr.reshape(4, 2)

array([[3, 4],
       [2, 5],
       [2, 5],
       [2, 2]])

In [118]:
arr.reshape(2, 4, 1)

array([[[3],
        [4],
        [2],
        [5]],

       [[2],
        [5],
        [2],
        [2]]])

# Joining Array

In [134]:
# concatenating the array
a = np.array([1, 1, 1, 1])
b = np.array([2, 2, 2, 2])

concat_arr = np.concatenate((a, b)) # default axis = 0 can't do axis = 0 in 1D array because its shape is (n,)
concat_arr

array([1, 1, 1, 1, 2, 2, 2, 2])

In [136]:
a = np.array([[2, 4, 2], [3, 2, 4]])
b = np.array([[5, 2, 5], [2, 2, 1]])
np.concatenate((a, b), axis = 0)

array([[2, 4, 2],
       [3, 2, 4],
       [5, 2, 5],
       [2, 2, 1]])

In [137]:
np.concatenate((a, b), axis=1)

array([[2, 4, 2, 5, 2, 5],
       [3, 2, 4, 2, 2, 1]])

# splitting Array

In [140]:
arr = np.array([1, 2, 3, 4, 5])
np.split(arr, 4)

ValueError: array split does not result in an equal division

In [142]:
np.array_split(arr, 4)

[array([1, 2]), array([3]), array([4]), array([5])]

# splitting 2D array( axis=0 )

In [145]:
split_array_2D = np.array([[3, 4, 5], [2, 4, 5], [2, 5, 2], [10, 11, 12], [23, 24, 25], [31, 32, 43]])
split_array_2D

array([[ 3,  4,  5],
       [ 2,  4,  5],
       [ 2,  5,  2],
       [10, 11, 12],
       [23, 24, 25],
       [31, 32, 43]])

In [146]:
np.array_split(split_array_2D, 3)

[array([[3, 4, 5],
        [2, 4, 5]]),
 array([[ 2,  5,  2],
        [10, 11, 12]]),
 array([[23, 24, 25],
        [31, 32, 43]])]

In [147]:
np.array_split(split_array_2D, 4)

[array([[3, 4, 5],
        [2, 4, 5]]),
 array([[ 2,  5,  2],
        [10, 11, 12]]),
 array([[23, 24, 25]]),
 array([[31, 32, 43]])]

In [151]:
np.split(split_array_2D, 3)

[array([[3, 4, 5],
        [2, 4, 5]]),
 array([[ 2,  5,  2],
        [10, 11, 12]]),
 array([[23, 24, 25],
        [31, 32, 43]])]

In [153]:
np.array_split(split_array_2D, 3, axis=1)

[array([[ 3],
        [ 2],
        [ 2],
        [10],
        [23],
        [31]]),
 array([[ 4],
        [ 4],
        [ 5],
        [11],
        [24],
        [32]]),
 array([[ 5],
        [ 5],
        [ 2],
        [12],
        [25],
        [43]])]

In [154]:
np.array_split(split_array_2D, 4, axis=1)

[array([[ 3],
        [ 2],
        [ 2],
        [10],
        [23],
        [31]]),
 array([[ 4],
        [ 4],
        [ 5],
        [11],
        [24],
        [32]]),
 array([[ 5],
        [ 5],
        [ 2],
        [12],
        [25],
        [43]]),
 array([], shape=(6, 0), dtype=int32)]

In [155]:
np.split(split_array_2D, 4, axis=1)

ValueError: array split does not result in an equal division

# Numpy universal funcitons (ufuncs)
* looping over the array ot perform repeated task like addition, substraction , etc on each aray element are common.
* computation time to perform such repeated task increases with relatively larger data.
* Numpy makes this faster by using vectorized operationn, implemented through ufuncs.
* types 
    1. Unary Ufuncs (Operates on single inputs)
    2. Binary Ufucs (Operates on two inputs)

# computation time without Ufuncs

In [156]:
import time

In [161]:
x1 = np.arange(1, 10000000)
x2 = np.arange(1, 10000000)

# array to hold multiplications
mul = np.zeros(x1.shape)

start_time = time.process_time()

for i in range(len(x1)):
    mul[i] = x1[i] * x2[i]

end_time = time.process_time()

print(end_time - start_time)



C:\Users\Hp\AppData\Local\Temp\ipykernel_16700\934944000.py:10: RuntimeWarning: overflow encountered in scalar multiply
  mul[i] = x1[i] * x2[i]


26.625


# Broadcasting

In [162]:
a = np.array([1, 2, 3])
b = 2
print(a + b)

[3 4 5]


In [163]:
a * b

array([2, 4, 6])

In [166]:
# broadcasting with 1D and 2D array
a = np.array([1, 2, 4])
b = np.array([[10], [20], [40]])
print(a.shape, b.shape)

(3,) (3, 1)


In [167]:
a + b

array([[11, 12, 14],
       [21, 22, 24],
       [41, 42, 44]])

In [168]:
# broadcasting with incompatible shapes

a = np.array([2, 4])
b = np.array([2, 5, 2])

In [169]:
a + b

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [171]:
np.eye(N=3, k=0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])