# Numpy
* stands for numerical Python
* numpy is a python library used for working with arrays
* has function for working in domain of linear algebra, fourier transform and matrices
* numpy array is a collection of homogeneous data types stored in contiguous memory location
* written partially in python, but parts that require fast computation are written in C or C++

#  Why is Numpy so fast?
* An array is a collection of homogeneous data types that are stored in contiguous memory location
* Vectorized operations are possible in Numpy
* Numpy package integrates C, C++ and Fortran codes in python

In [1]:
import numpy as np

# Create numpy array vai 1D list

In [3]:
np.random.seed(0)
list_1 = np.random.randint(low=1, high=20, size=10)
arr = np.array(list_1)
print(arr)

[13 16  1  4  4  8 10 19  5  7]


# Checking the type of array

In [5]:
type(arr)

numpy.ndarray

# create numpy via 2D list

In [6]:
list_2 = np.random.randint(low=10, high=30, size=10)
arr_2 = np.array([list_1, list_2], dtype="float32")
arr_2

array([[13., 16.,  1.,  4.,  4.,  8., 10., 19.,  5.,  7.],
       [22., 11., 16., 17., 24., 27., 15., 23., 18., 19.]], dtype=float32)

# .shape

In [8]:
arr_2.shape

(2, 10)

# .ndim

In [10]:
arr_2.ndim

2

# .zeros()

In [13]:
np.zeros((3, 3), dtype="int")

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [14]:
np.zeros(10, dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.zeros((5, 2), dtype="int")

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

# .ones()

In [17]:
np.ones(3, dtype="int")

array([1, 1, 1])

In [18]:
np.ones([3, 5], dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# .full()

In [19]:
np.full([2, 3], 3.23)

array([[3.23, 3.23, 3.23],
       [3.23, 3.23, 3.23]])

In [22]:
np.full([2, 2], ["white", "green"])

array([['white', 'green'],
       ['white', 'green']], dtype='<U5')

In [24]:
np.full((2, 10), [list_1, list_2])

array([[13, 16,  1,  4,  4,  8, 10, 19,  5,  7],
       [22, 11, 16, 17, 24, 27, 15, 23, 18, 19]])

# .arange()

In [25]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [26]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(3, 23)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22])

# .random()

In [29]:
np.random.random((3, 5))

array([[0.36824154, 0.95715516, 0.14035078, 0.87008726, 0.47360805],
       [0.80091075, 0.52047748, 0.67887953, 0.72063265, 0.58201979],
       [0.53737323, 0.75861562, 0.10590761, 0.47360042, 0.18633234]])

In [36]:
np.random.randint(3, 534)

131

In [38]:
np.random.random((2, 5))

array([[0.32414101, 0.14967487, 0.22232139, 0.38648898, 0.90259848],
       [0.44994999, 0.61306346, 0.90234858, 0.09928035, 0.96980907]])

# .normal()

In [42]:
data = np.random.normal(loc=3, scale=1, size=(3, 3))
data

array([[3.11699649, 0.91964866, 2.35737949],
       [3.68702441, 5.0385073 , 2.41123444],
       [0.28176742, 2.21052277, 3.25369995]])

# .randint()

In [43]:
np.random.randint(low=0, high=10, size=(3, 3))

array([[2, 4, 7],
       [1, 9, 6],
       [4, 6, 8]])

# Creating Sample Array

In [46]:
sample_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sample_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
# Printing the dimension of numpy
sample_array.ndim

2

In [65]:
sample_array.shape

(3, 3)

In [57]:
reshape_array = sample_array.reshape(1, 3, 3)
reshape_array

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [58]:
reshape_array.shape

(1, 3, 3)

In [59]:
reshape_array.ndim

3

In [60]:
reshape_array.size

9

In [62]:
reshape_array.dtype

dtype('int32')

In [63]:
reshape_array.itemsize

4

In [66]:
np.array(["Alone", "Home", 10, True, 0, 44.2])

array(['Alone', 'Home', '10', 'True', '0', '44.2'], dtype='<U32')

In [1]:
import numpy as np

In [7]:
type(np.array((3, 4)))

numpy.ndarray

# Function that converts list into another list which act as array like structure

In [68]:
def to_array(data):
    """
    Function that converts the list data into array like structure

    args: takes argument as list of elements

    return : return data in specific datatype
    """

    string = []
    flo = []
    integer = []
    boolean = []
    # tuple = []
    # list = []

    # checking type of data and appending in respective datatype
    for item in data:
        if isinstance(item, str):
            string.append(item)
        elif isinstance(item, float):
            flo.append(item)
        elif isinstance(item, bool):
            boolean.append(item)
        elif isinstance(item, int):
            integer.append(item)

    # print(len(string), len(flo), len(integer), len(boolean))

    # if datatype of any data is string convert all data into string
    if len(string) > 0:
        arr_data = [str(i) for i in data]
    
    # if there is no string and datatype contains float numbers then convert all data into float numbers
    elif len(flo) > 0:
        arr_data = [float(i) for i in data]
    
    # if there is no sting and float datatype in the data then convert all the data into int 
    elif len(integer) > 0:
        arr_data = [int(i) for i in data]
    
    # else keep the boolean data same
    elif len(boolean) > 0:
        arr_data = data

    return arr_data


# Testing

In [69]:
# data that contains string
to_array(data=[True, 2.3, "Home", "Alone", 34])

['True', '2.3', 'Home', 'Alone', '34']

In [70]:
# data that contains float but not string
to_array(data=[4, True, False, 45, 2.2])

[4.0, 1.0, 0.0, 45.0, 2.2]

In [71]:
# data that contains int but not float and string
to_array(data=[4, False, 2, 5, 2, True])

[4, 0, 2, 5, 2, 1]

In [73]:
# data that contains bool only
to_array(data=[True, False, False])

[True, False, False]

In [14]:
np.array([[True, 0, 3], [True, 0, 9.3]])


array([[1. , 0. , 3. ],
       [1. , 0. , 9.3]])

In [26]:
isinstance(True, int)

True

In [28]:
isinstance(False, int)

True

In [58]:
np.array([[3, 54, "10"], [2, 4, 9.2]])

array([['3', '54', '10'],
       ['2', '4', '9.2']], dtype='<U32')

In [46]:
float(2.3)

2.3

In [62]:
np.array([3, "2", 2])

array(['3', '2', '2'], dtype='<U11')

In [67]:
datas = ["3", 3, 2.3]
isinstance(datas, str)

True